using Native.OpenApi;

namespace Functions.OpenApi;

/// <summary>
/// Loads OpenAPI document parts from embedded common YAML resources
/// and from the 3 producer Lambda partial YAML specs.
/// 
/// The partial specs (admin.yaml, identity.yaml, openid.yaml) are generated by
/// the NativeLambdaRouter Source Generator in each producer project and then
/// committed/copied into this project's openapi/partials/ directory.
/// </summary>
public sealed class MultiLambdaDocumentLoader : OpenApiDocumentLoaderBase
{
    public MultiLambdaDocumentLoader()
        : base(new OpenApiResourceReader(typeof(MultiLambdaDocumentLoader).Assembly, "Functions.OpenApi."))
    {
    }

    public override IReadOnlyList<OpenApiDocumentPart> LoadCommon()
    {
        return
        [
            Load("schemas", "openapi/common/schemas.yaml"),
            Load("responses", "openapi/common/responses.yaml"),
            Load("security", "openapi/common/security.yaml")
        ];
    }

    public override IReadOnlyList<OpenApiDocumentPart> LoadPartials()
    {
        return
        [
            Load("admin", "openapi/partials/admin.yaml"),
            Load("identity", "openapi/partials/identity.yaml"),
            Load("openid", "openapi/partials/openid.yaml")
        ];
    }
}
