openapi: "3.1.0"

info:
  title: "Admin API"
  version: "1.0.0"

paths:
  /v1/admin/users:
    get:
      operationId: getV1AdminUsers
      summary: "Get ListUsers"
      tags:
        - V1
      security:
        - JwtBearer: []
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListUsersResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalServerError"
    post:
      operationId: postV1AdminUsers
      summary: "Create CreateUser"
      tags:
        - V1
      security:
        - JwtBearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserCommand"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateUserResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /v1/admin/users/{id}:
    delete:
      operationId: deleteV1AdminUsersById
      summary: "Delete DeleteUser"
      tags:
        - V1
      security:
        - JwtBearer: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteUserResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  schemas:
    CreateUserCommand:
      type: object
      description: "Request type - properties to be documented"
    CreateUserResponse:
      type: object
      description: "Response type - properties to be documented"
    DeleteUserCommand:
      type: object
      description: "Request type - properties to be documented"
    DeleteUserResponse:
      type: object
      description: "Response type - properties to be documented"
    ListUsersCommand:
      type: object
      description: "Request type - properties to be documented"
    ListUsersResponse:
      type: object
      description: "Response type - properties to be documented"
