openapi: "3.1.0"

info:
  title: "Identity API"
  version: "1.0.0"

paths:
  /v1/auth/login:
    post:
      operationId: postV1AuthLogin
      summary: "Create Login"
      tags:
        - V1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginCommand"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /v1/auth/refresh:
    post:
      operationId: postV1AuthRefresh
      summary: "Create RefreshToken"
      tags:
        - V1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshTokenCommand"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RefreshTokenResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /v1/auth/register:
    post:
      operationId: postV1AuthRegister
      summary: "Create Register"
      tags:
        - V1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterCommand"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  schemas:
    LoginCommand:
      type: object
      description: "Request type - properties to be documented"
    LoginResponse:
      type: object
      description: "Response type - properties to be documented"
    RefreshTokenCommand:
      type: object
      description: "Request type - properties to be documented"
    RefreshTokenResponse:
      type: object
      description: "Response type - properties to be documented"
    RegisterCommand:
      type: object
      description: "Request type - properties to be documented"
    RegisterResponse:
      type: object
      description: "Response type - properties to be documented"
