openapi: "3.1.0"
info:
  title: OpenID Connect API
  version: "1.0.0"
paths:
  /v1/openid/discovery:
    get:
      summary: OpenID Connect Discovery
      operationId: getOpenIdConfiguration
      tags:
        - OpenID
      security:
        - JwtBearer: []
      responses:
        "200":
          description: OpenID Configuration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OpenIdConfigurationResponse"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /v1/openid/jwks:
    get:
      summary: JSON Web Key Set
      operationId: getJwks
      tags:
        - OpenID
      security:
        - JwtBearer: []
      responses:
        "200":
          description: JWKS response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JwksResponse"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /v1/openid/token:
    post:
      summary: Exchange authorization code for tokens
      operationId: exchangeToken
      tags:
        - OpenID
      security:
        - JwtBearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenCommand"
      responses:
        "200":
          description: Token response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    OpenIdConfigurationResponse:
      type: object
      properties:
        issuer:
          type: string
        authorization_endpoint:
          type: string
        token_endpoint:
          type: string
        jwks_uri:
          type: string
        response_types_supported:
          type: array
          items:
            type: string
        subject_types_supported:
          type: array
          items:
            type: string
        id_token_signing_alg_values_supported:
          type: array
          items:
            type: string
    JwksResponse:
      type: object
      properties:
        keys:
          type: array
          items:
            $ref: "#/components/schemas/JwkKey"
    JwkKey:
      type: object
      properties:
        kty:
          type: string
        use:
          type: string
        kid:
          type: string
        "n":
          type: string
        e:
          type: string
    TokenCommand:
      type: object
      properties:
        grant_type:
          type: string
        code:
          type: string
        redirect_uri:
          type: string
      required:
        - grant_type
        - code
        - redirect_uri
    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: integer
          format: int64
        id_token:
          type: string
