openapi: "3.1.0"

info:
  title: "OpenID Connect API"
  version: "1.0.0"

paths:
  /.well-known/jwks.json:
    get:
      operationId: get.well-knownJwks.json
      summary: "Get Jwks"
      tags:
        - .well-known
      security: []
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JwksResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /.well-known/openid-configuration:
    get:
      operationId: get.well-knownOpenid-configuration
      summary: "Get OpenIdConfiguration"
      tags:
        - .well-known
      security: []
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OpenIdConfigurationResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /v1/openid/token:
    post:
      operationId: postV1OpenidToken
      summary: "Create Token"
      tags:
        - V1
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenCommand"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  schemas:
    JwksCommand:
      type: object
      description: "Request type - properties to be documented"
    JwksResponse:
      type: object
      description: "Response type - properties to be documented"
    OpenIdConfigurationCommand:
      type: object
      description: "Request type - properties to be documented"
    OpenIdConfigurationResponse:
      type: object
      description: "Response type - properties to be documented"
    TokenCommand:
      type: object
      description: "Request type - properties to be documented"
    TokenResponse:
      type: object
      description: "Response type - properties to be documented"
